# Generated by Django 4.0.6 on 2022-07-14 10:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0005_alter_loginmodel_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginModel',
            new_name='Customer',
        ),
    ]
